using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace StArray.ModManager.SourceGenerator;

/// <summary>为 NativeImportAttribute 生成 resolver-backed partial methods。</summary>
[Generator]
public sealed class NativeImportGenerator : IIncrementalGenerator
{
    private const string AttributeName = "StArray.ModManager.NativeImportAttribute";

    private sealed class ImportInfo
    {
        public string ContainingType { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string ClassName { get; set; } = "";
        public bool IsStatic { get; set; }
        public string MethodName { get; set; } = "";
        public string ReturnType { get; set; } = "";
        public ImmutableArray<(string Type, string Name)> Parameters { get; set; }
        public string Library { get; set; } = "";
        public string EntryPoint { get; set; } = "";
        public string Convention { get; set; } = "Cdecl";
        public string CharSet { get; set; } = "Ansi";
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var imports = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is MethodDeclarationSyntax method &&
                    method.AttributeLists.Count != 0,
                static (ctx, _) => GetImport(ctx))
            .Where(static import => import is not null)!;

        context.RegisterSourceOutput(imports.Collect(), static (spc, values) =>
            Generate(spc, values!));
    }

    private static ImportInfo? GetImport(GeneratorSyntaxContext context)
    {
        var method = (MethodDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(method) is not IMethodSymbol symbol)
            return null;

        var attr = symbol.GetAttributes().FirstOrDefault(IsImport);
        if (attr is null)
            return null;

        var type = symbol.ContainingType;
        var classAttribute = type.GetAttributes().FirstOrDefault(IsImport);
        var library = GetString(attr, "Library") ?? GetCtorString(classAttribute);
        if (string.IsNullOrWhiteSpace(library))
            return null;

        var parameters = symbol.Parameters
            .Select(parameter => (
                parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                parameter.Name))
            .ToImmutableArray();

        return new ImportInfo
        {
            ContainingType = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Namespace = type.ContainingNamespace.IsGlobalNamespace ? "" : type.ContainingNamespace.ToDisplayString(),
            ClassName = type.Name,
            IsStatic = type.IsStatic,
            MethodName = symbol.Name,
            ReturnType = symbol.ReturnType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            Parameters = parameters,
            Library = library!,
            EntryPoint = GetString(attr, "EntryPoint") ?? symbol.Name,
            Convention = GetEnumName(attr, "Convention") ?? "Cdecl",
            CharSet = GetEnumName(attr, "CharSet") ?? "Ansi",
        };
    }

    private static bool IsImport(AttributeData attribute) =>
        attribute.AttributeClass?.ToDisplayString() == AttributeName;

    private static string? GetCtorString(AttributeData? attribute) =>
        attribute?.ConstructorArguments.FirstOrDefault().Value as string;

    private static string? GetString(AttributeData attribute, string name) =>
        attribute.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value.Value as string;

    private static string? GetEnumName(AttributeData attribute, string name)
    {
        var value = attribute.NamedArguments.FirstOrDefault(pair => pair.Key == name).Value;
        if (value.Value is null)
            return null;
        if (name == "Convention")
        {
            return Convert.ToInt32(value.Value) switch
            {
                3 => "StdCall",
                4 => "ThisCall",
                5 => "FastCall",
                _ => "Cdecl",
            };
        }
        return Convert.ToInt32(value.Value) switch
        {
            3 => "Unicode",
            4 => "Auto",
            _ => "Ansi",
        };
    }

    private static void Generate(SourceProductionContext context, ImmutableArray<ImportInfo?> imports)
    {
        foreach (var group in imports.Where(static item => item is not null).Select(item => item!).GroupBy(i => i.ContainingType))
        {
            var first = group.First();
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");
            if (!string.IsNullOrEmpty(first.Namespace))
            {
                builder.Append("namespace ").Append(first.Namespace).AppendLine(";");
            }
            builder.AppendLine("using global::System.Runtime.InteropServices;");
            builder.AppendLine();
            builder.Append("public ").Append(first.IsStatic ? "static " : "")
                .Append("partial class ").Append(first.ClassName).AppendLine();
            builder.AppendLine("{");

            foreach (var import in group)
            {
                var delegateName = "__NativeImport_" + import.MethodName;
                var fieldName = "__native_" + import.MethodName;
                var parameters = string.Join(", ", import.Parameters.Select(p =>
                    $"{SimplifyType(p.Type)} @{p.Name}"));
                var arguments = string.Join(", ", import.Parameters.Select(p => "@" + p.Name));
                builder.AppendLine($"    [UnmanagedFunctionPointer(CallingConvention.{import.Convention})]");
                builder.AppendLine($"    private delegate {SimplifyType(import.ReturnType)} {delegateName}({parameters});");
                builder.AppendLine($"    private static {delegateName}? {fieldName};");
                builder.AppendLine();
                builder.Append("    public ").Append(import.IsStatic ? "static " : "")
                    .Append("partial ").Append(SimplifyType(import.ReturnType)).Append(' ')
                    .Append(import.MethodName).Append('(').Append(parameters).AppendLine(")");
                builder.AppendLine("    {");
                builder.AppendLine($"        var callback = {fieldName};");
                builder.AppendLine("        if (callback == null)");
                builder.AppendLine("        {");
                builder.AppendLine($"            var address = global::StArray.ModManager.Runtime.HookHelper.GetFunction(\"{Escape(import.Library)}\", \"{Escape(import.EntryPoint)}\");");
                builder.AppendLine("            if (address == nint.Zero) throw new MissingMethodException();");
                builder.AppendLine($"            callback = Marshal.GetDelegateForFunctionPointer<{delegateName}>(address);");
                builder.AppendLine($"            {fieldName} = callback;");
                builder.AppendLine("        }");
                if (SimplifyType(import.ReturnType) == "void")
                    builder.AppendLine($"        callback({arguments});");
                else
                    builder.AppendLine($"        return callback({arguments});");
                builder.AppendLine("    }");
            }

            builder.AppendLine("}");
            context.AddSource("NativeImport_" + first.ClassName + ".g.cs", builder.ToString());
        }
    }

    private static string SimplifyType(string type) => type switch
    {
        "global::System.Void" => "void",
        "global::System.IntPtr" => "nint",
        "global::System.UIntPtr" => "nuint",
        _ when type.StartsWith("global::", StringComparison.Ordinal) => type.Substring(8),
        _ => type,
    };

    private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
